name: "get-info"

on:
  workflow_dispatch:

jobs:
  extract_worker_info:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Get storage
        shell: bash
        run: |
          sudo whoami
          echo
          sudo lsblk
          echo
          sudo df -h
          echo
          sudo ls -ahl /mnt
          echo
          sudo du -h /mnt
          echo
          sudo cat /proc/cpuinfo

      - name: Get memory
        shell: bash
        run: |
          sudo free -h
          echo
          sudo swapon --show

      - name: Remove swap
        shell: bash
        run: |
          sudo swapoff -a
          echo
          sudo swapon --show
          echo
          sudo rm /mnt/swapfile
          echo
          sudo df -h

      - name: Create new swap
        shell: bash
        run: |
          sudo fallocate -l 4G /mnt/new-swapfile
          sudo chmod 600 /mnt/new-swapfile
          sudo mkswap /mnt/new-swapfile
          sudo swapon /mnt/new-swapfile

      - name: "Environment varirables"
        shell: bash
        run: |
          echo "${PWD}"
          echo "$GITHUB_WORKSPACE"
          echo "${{ github.workspace }}"
