name: "get-info"

on:
  push:
    branches:
      - "main"
      - "master"

jobs:
  extract_worker_info:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Get storage
        shell: bash
        run: |
          whoami
          echo
          lsblk
          echo
          df -h
          echo
          ls -ahl /mnt
          echo
          du -h /mnt

      - name: Get memory
        shell: bash
        run: |
          free -h
          echo
          swapon --show

      - name: Remove swap
        shell: bash
        run: |
          swapoff -a
          echo
          swapon --show
          echo
          rm /mnt/swapfile
          echo
          df -h

      - name: Create new swap
        shell: bash
        run: |
          fallocate -l 4G /mnt/new-swapfile
          chmod 600 /mnt/new-swapfile
          mkswap /mnt/new-swapfile
          swapon /mnt/new-swapfile
