name: "get-info"

on:
  workflow_dispatch:

jobs:
  extract_worker_info:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Get user info
        shell: bash
        run: |
          whoami
          echo
          sudo whoami
          echo
          cat /etc/passwd

      - name: Get CPU info
        shell: bash
        run: |
          sudo cat /proc/cpuinfo

      - name: Get memory and swap
        shell: bash
        run: |
          sudo free -h
          echo
          sudo swapon --show

      - name: Get storage
        shell: bash
        run: |
          sudo lsblk
          echo
          sudo df -h
