name: "replace-swapfile"

on:
  workflow_dispatch:

jobs:
  replace_swapfile:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Get info
        shell: bash
        run: |
          sudo free -h
          echo
          sudo swapon --show
          echo
          sudo lsblk
          echo
          sudo df -h

      - name: Save swapfile path
        shell: bash
        run: |
          nbr_swapfiles="$(sudo swapon --show --noheadings | wc -l)"
          if [ "${nbr_swapfiles}" -eq 0 ]; then
            echo "No swapfile path found; using default"
            echo "SWAPFILE_PATH=/mnt/swapfile" >> $GITHUB_ENV
          else
            echo "SWAPFILE_PATH=$(sudo swapon --show --noheadings | head -n 1 | cut -d' ' -f1)" >> $GITHUB_ENV
            if [ "${nbr_swapfiles}" -eq 1 ]; then
              echo "Removing old swapfile  ${SWAPFILE_PATH}"
            else
              echo "More than one swapfile found; only removing ${SWAPFILE_PATH}"
            fi
          fi

      - name: Remove swap
        shell: bash
        run: |
          sudo swapoff -a
          echo
          sudo swapon --show
          echo
          if [ -f "${SWAPFILE_PATH}" ]; then
            sudo rm -v "${SWAPFILE_PATH}"
            echo
          fi
          sudo df -h
          echo
          sudo swapon --show

      - name: Create new swap
        shell: bash
        run: |
          sudo fallocate -l 4G "${SWAPFILE_PATH}"
          sudo chmod 600 "${SWAPFILE_PATH}"
          sudo mkswap "${SWAPFILE_PATH}"
          sudo swapon "${SWAPFILE_PATH}"

      - name: Show new memory and storage setup
        shell: bash
        run: |
          sudo free -h
          echo
          sudo swapon --show
          echo
          sudo df -h
